import { TransactionsDTO } from './transactions-table-schema'
import {
    TRANSACTION_METHODS,
    TRANSACTION_ACCOUNTS,
    TRANSACTION_CATEGORIES,
    TRANSACTION_RESPONSIBLE_PARTIES,
} from '@/lib/consts/transactionOptions'

const commonOptions = {
    methods: TRANSACTION_METHODS,
    accounts: TRANSACTION_ACCOUNTS,
    categories: TRANSACTION_CATEGORIES,
    responsibleParties: TRANSACTION_RESPONSIBLE_PARTIES,
}

const baseTransactions = [
    {
        id: 1,
        description: 'Netflix Subscription',
        price: 45.9,
        installment: '1/1',
        date: '2024-01-05',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Entertainment',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: true,
    },
    {
        id: 2,
        description: 'Supermarket - Carrefour',
        price: 328.45,
        installment: '1/1',
        date: '2024-01-08',
        method: 'Debit Card',
        account: 'Santander',
        category: 'Groceries',
        responsibleParty: 'Jane Smith',
        paid: true,
        recurrent: false,
    },
    {
        id: 3,
        description: 'Gym Membership',
        price: 89.0,
        installment: '1/1',
        date: '2024-01-10',
        method: 'Direct Debit',
        account: 'Itau',
        category: 'Health',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: true,
    },
    {
        id: 4,
        description: 'Smartphone - iPhone 15',
        price: 5999.0,
        installment: '3/12',
        date: '2024-01-12',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Electronics',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: false,
    },
    {
        id: 5,
        description: 'Electric Bill',
        price: 187.32,
        installment: '1/1',
        date: '2024-01-15',
        method: 'Bank Transfer',
        account: 'Bradesco',
        category: 'Utilities',
        responsibleParty: 'Jane Smith',
        paid: true,
        recurrent: true,
    },
    {
        id: 6,
        description: 'Restaurant - Pizza Night',
        price: 145.8,
        installment: '1/1',
        date: '2024-01-18',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Food & Dining',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: false,
    },
    {
        id: 7,
        description: 'Car Insurance',
        price: 420.0,
        installment: '1/1',
        date: '2024-01-20',
        method: 'Direct Debit',
        account: 'Itau',
        category: 'Insurance',
        responsibleParty: 'Jane Smith',
        paid: true,
        recurrent: true,
    },
    {
        id: 8,
        description: 'Gasoline',
        price: 250.0,
        installment: '1/1',
        date: '2024-01-22',
        method: 'Debit Card',
        account: 'Santander',
        category: 'Transportation',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: false,
    },
    {
        id: 9,
        description: 'Spotify Premium',
        price: 21.9,
        installment: '1/1',
        date: '2024-01-23',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Entertainment',
        responsibleParty: 'Jane Smith',
        paid: true,
        recurrent: true,
    },
    {
        id: 10,
        description: 'Doctor Appointment',
        price: 350.0,
        installment: '1/1',
        date: '2024-01-25',
        method: 'Credit Card',
        account: 'Itau',
        category: 'Health',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: false,
    },
    {
        id: 11,
        description: 'Internet Bill',
        price: 119.9,
        installment: '1/1',
        date: '2024-02-01',
        method: 'Direct Debit',
        account: 'Bradesco',
        category: 'Utilities',
        responsibleParty: 'Jane Smith',
        paid: true,
        recurrent: true,
    },
    {
        id: 12,
        description: 'Clothing Store - Zara',
        price: 385.5,
        installment: '2/3',
        date: '2024-02-03',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Shopping',
        responsibleParty: 'Jane Smith',
        paid: true,
        recurrent: false,
    },
    {
        id: 13,
        description: 'Pet Store - Dog Food',
        price: 180.0,
        installment: '1/1',
        date: '2024-02-05',
        method: 'Debit Card',
        account: 'Santander',
        category: 'Pets',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: false,
    },
    {
        id: 14,
        description: 'Pharmacy',
        price: 75.4,
        installment: '1/1',
        date: '2024-02-07',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Health',
        responsibleParty: 'Jane Smith',
        paid: true,
        recurrent: false,
    },
    {
        id: 15,
        description: 'Uber Rides',
        price: 95.3,
        installment: '1/1',
        date: '2024-02-10',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Transportation',
        responsibleParty: 'John Doe',
        paid: true,
        recurrent: false,
    },
    {
        id: 16,
        description: 'Book Store - Amazon',
        price: 127.8,
        installment: '1/1',
        date: '2024-02-12',
        method: 'Credit Card',
        account: 'Itau',
        category: 'Education',
        responsibleParty: 'Jane Smith',
        paid: false,
        recurrent: false,
    },
    {
        id: 17,
        description: 'Water Bill',
        price: 68.5,
        installment: '1/1',
        date: '2024-02-15',
        method: 'Bank Transfer',
        account: 'Bradesco',
        category: 'Utilities',
        responsibleParty: 'John Doe',
        paid: false,
        recurrent: true,
    },
    {
        id: 18,
        description: 'Movie Theater',
        price: 78.0,
        installment: '1/1',
        date: '2024-02-17',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Entertainment',
        responsibleParty: 'Jane Smith',
        paid: false,
        recurrent: false,
    },
    {
        id: 19,
        description: 'Laptop - Dell Inspiron',
        price: 3499.0,
        installment: '5/10',
        date: '2024-02-18',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Electronics',
        responsibleParty: 'John Doe',
        paid: false,
        recurrent: false,
    },
    {
        id: 20,
        description: 'Hair Salon',
        price: 120.0,
        installment: '1/1',
        date: '2024-02-20',
        method: 'Debit Card',
        account: 'Santander',
        category: 'Personal Care',
        responsibleParty: 'Jane Smith',
        paid: false,
        recurrent: false,
    },
    {
        id: 21,
        description: 'Coffee Shop',
        price: 35.6,
        installment: '1/1',
        date: '2024-02-22',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Food & Dining',
        responsibleParty: 'John Doe',
        paid: false,
        recurrent: false,
    },
    {
        id: 22,
        description: 'Phone Bill',
        price: 89.9,
        installment: '1/1',
        date: '2024-02-25',
        method: 'Direct Debit',
        account: 'Itau',
        category: 'Utilities',
        responsibleParty: 'Jane Smith',
        paid: false,
        recurrent: true,
    },
    {
        id: 23,
        description: 'Hardware Store',
        price: 215.4,
        installment: '1/1',
        date: '2024-02-26',
        method: 'Credit Card',
        account: 'Nubank',
        category: 'Home & Garden',
        responsibleParty: 'John Doe',
        paid: false,
        recurrent: false,
    },
    {
        id: 24,
        description: 'Veterinarian',
        price: 280.0,
        installment: '1/1',
        date: '2024-02-28',
        method: 'Credit Card',
        account: 'Itau',
        category: 'Pets',
        responsibleParty: 'Jane Smith',
        paid: false,
        recurrent: false,
    },
    {
        id: 25,
        description: 'Parking Fee',
        price: 45.0,
        installment: '1/1',
        date: '2024-03-01',
        method: 'Debit Card',
        account: 'Santander',
        category: 'Transportation',
        responsibleParty: 'John Doe',
        paid: false,
        recurrent: false,
    },
]

export const mockTransactionsData: TransactionsDTO = baseTransactions.map(
    (t) => ({ ...t, ...commonOptions }),
)
